= Task 3 

The submission deadline is *Monday 16.12.2019 22 pm*. After that the solutions will be archived.

==== Assignment


On the server *`fray1`* or *`fray3`*, in the directory *`tyden12`* ( directory createdin task 1), create the following

. In any way ("manually" or by script) make sure that:
** there will be a file with the name *HD* in the directory *`tyden12`*,
** this file will contain a single line with your username,
** the output from command *`ls -l HD`* will contain the number *5* in the second column,
** there will be a maximum of 3 *regular* files, including an HD file, in the directory *`week12`* 

. Write a shell script that creates a symbolic link string in this directory such that:
** the first link (e.g. named *sln1*) refers to the file `/etc/hosts`,
** the second link (e.g. named *sln2*) refers to the previous link *`sln1`*,
** the thirds link (e.g. named *sln3*) refers to the previous link *`sln2`*, and so on.
** The length of this string is specified by a number that is a parameter of the script..
** An example of a created string of length 3 is in the example below.

==== Podmínky správného řešení


* Pokud budete vytvářet nějaké pracovní adresáře, musí být všechny v rámci adresáře *`~/ulohy/tyden12`*.
* Skript, soubor HD a všechny symbolické linky musí být uloženy v adresáři *`~/ulohy/tyden12`*


==== Příklad


Pokud se skript na vytvoření řetězce linků jmenuje `uloha-linky` mohl by výstup příkazu *`ls -la`* vypadat například takto:


----
cd ~/ulohy/tyden12
ls -la
drwx------   3 muzikar  zam            2 Feb 28 17:25 .
drwx------   4 muzikar  zam            4 Nov 15 10:05 ..
-rw-------   5 muzikar  zam            8 Oct 25 22:29 HD
drwx------   2 muzikar  zam            6 Nov 15 10:10 pracovni_adr
lrwxrwxrwx   1 muzikar  zam           10 Nov 15 10:11 sln1 -> /etc/hosts
lrwxrwxrwx   1 muzikar  zam            4 Nov 15 10:12 sln2 -> sln1
lrwxrwxrwx   1 muzikar  zam            4 Nov 15 10:12 sln3 -> sln2
-rwx------   1 muzikar  zam          328 Oct 25 22:20 uloha-linky
----


==== Bonusová otázka


Zamyslete se nad tím, proč je z tohoto výpisu zcela evidentní, že uživatel muzikar nesplnil zadání 1. úlohy :-)  +
Tedy splnil pouze částečně - klíč k odpovědi je v druhé řádce výpisu.
