= Task 3 

The submission deadline is *Monday 16.12.2019 22 pm*. After that the solutions will be archived.

==== Assignment


On the server *`fray1`* or *`fray3`*, in the directory *`tyden12`* ( directory created in task 1), create the following

. In any way ("manually" or by script) make sure that:
** there will be a file with the name *HD* in the directory *`tyden12`*,
** this file will contain a single line with your username,
** the output from command *`ls -l HD`* will contain the number *5* in the second column,
** there will be a maximum of 3 *regular* files, including an HD file, in the directory *`week12`*.

. Create a shell script that creates a symbolic link string in this directory such that:
** the first link (e.g. named *sln1*) refers to the file `/etc/hosts`,
** the second link (e.g. named *sln2*) refers to the previous link *`sln1`*,
** the thirds link (e.g. named *sln3*) refers to the previous link *`sln2`*, and so on.
** The length of this string is specified by a number that is a parameter of the script.
** An example of a created string of length 3 is in the example below.

==== Conditions of correct solution


* If you create any working directories, they must all be within the directory *`~/ulohy/tyden12`*.
* The script, the HD file, and all symbolic links must be stored in the directory *`~/ulohy/tyden12`*


==== Example

For example, if the link string script is named `uloha-linky`, the output of *`ls -la`* might look like this:

----
cd ~/ulohy/tyden12
ls -la
drwx------   3 muzikar  zam            2 Feb 28 17:25 .
drwx------   4 muzikar  zam            4 Nov 15 10:05 ..
-rw-------   5 muzikar  zam            8 Oct 25 22:29 HD
drwx------   2 muzikar  zam            6 Nov 15 10:10 pracovni_adr
lrwxrwxrwx   1 muzikar  zam           10 Nov 15 10:11 sln1 -> /etc/hosts
lrwxrwxrwx   1 muzikar  zam            4 Nov 15 10:12 sln2 -> sln1
lrwxrwxrwx   1 muzikar  zam            4 Nov 15 10:12 sln3 -> sln2
-rwx------   1 muzikar  zam          328 Oct 25 22:20 uloha-linky
----


==== Bonus question

Consider why it is quite obvious from this statement that the user muzikar did not fulfill the assignment of the 1st task :-) +
Thus, it only partially fulfilled - the key to the answer is in the second line of the statement.
