= 1. News
:imagesdir: media

*1.11.2020 - Week 8*

[square]
* The lecture 7 will be available at the following link link:https://youtu.be/yD4qkQ7pVFg[YouTube]
* Seminars will be available at link:https://go.microsoft.com/fwlink/p/?LinkID=873020&lm=deeplink&lmsrc=homePageWeb&cmpid=WebSignIn[MS Teams]

*1.11.2020 - Week 7*

[square]
* The lecture 6 will be available at the following link link:https://youtu.be/VvPhIw2fGpM[YouTube]
* Seminars will be available at link:https://go.microsoft.com/fwlink/p/?LinkID=873020&lm=deeplink&lmsrc=homePageWeb&cmpid=WebSignIn[MS Teams]

*23.10.2020 - Week 6*

Classes (lecture and seminars) will be canceled the next Wednesday, October 28, 2020, because it will be a public holiday.

*20.10.2020 - Week 5*

.Links for the fourth week
|===
|Stream type | Link

|Lecture 5 (Wed 14.10. 7:30)
|https://youtu.be/mZ8FrDhdhWU

|Seminar 5 (Wed 14.10. 9:15)
|https://youtu.be/eeAa9dnJQuc

|Seminar 5 (Wed 14.10. 11:00)
|https://youtu.be/Jpf72x7hpT0

|Seminar 5(Wed 14.10. 12:45)
|https://youtu.be/VozkZzhCDdk
|===

A small test will take place at the beginning of the seminar. *Students can participate in the test only at the time when they have a seminar scheduled according to link:https://timetable.fit.cvut.cz/old/public/en/predmety/31/61/p3161206.html[KOS]*


*13.10.2020 - Week 4*

.Links for the fourth week
|===
|Stream type | Link

|Lecture 4 (Wed 14.10. 7:30)
|https://youtu.be/bDsl0rhDURQ

|Seminar 4 (Wed 14.10. 9:15)
|https://youtu.be/kmTrveziplE

|Seminar 4 (Wed 14.10. 11:00)
|https://youtu.be/kDDzZctDsVc

|Seminar 4 (Wed 14.10. 12:45)
|https://youtu.be/fg6p-i-Lyi8
|===


*5.10.2020 - Week 3*

.Links for the third week
|===
|Stream type | Link

|Lecture 3 (Wed 7.10. 7:30)
|https://youtu.be/K6E1PGsEV0k

|Seminar 3 (Wed 7.10. 9:15)
|https://youtu.be/seXtQqTT3N4

|Seminar 3 (Wed 7.10. 11:00)
|https://youtu.be/gTuT98qlyFs

|Seminar 3 (Wed 7.10. 12:45)
|https://youtu.be/hyhEMi2_eJI
|===


*29.9.2020 - Week 2*

.Links for the second week
|===
|Stream type | Link

|Lecture 2 (Wed 30.9. 7:30)
|https://youtu.be/JigA31MAMr0

|Seminar 2 (Wed 30.9. 9:15)
|https://youtu.be/Z7clsjyTbZw

|Seminar 2 (Wed 30.9. 11:00)
|https://youtu.be/b2olcwsROz8

|Seminar 2 (Wed 30.9. 12:45)
|https://youtu.be/tg8jdscUU8U
|===



*20.9.2020 - BI-ULI*

Module https://courses.fit.cvut.cz/BI-ULI[BI-ULI] (Introduction to Linux, 2 credits)  - auxiliary module especially for beginners. Students are enrolled in this course automatically and it will only depend on them whether they want to complete it (this is a bonus of gaining additional knowledge and additional credits).

*20.9.2020 - The course BIE-PS1 in winter semester 2020/21 (email sent via kos.cvut.cz)*

Dear students, regulations from the state, from the CTU rector and from the FIT dean do not allow contact classes and the both lectures and seminars must be implemented online. In BIE-PS1 I have made the following decisions:

The lectures and seminars will be realized as *live streams via Youtube in the scheduled time* (see the https://timetable.fit.cvut.cz/old/public/en/predmety/31/61/p3161206.html[timetable.fit.cvut.cz]). The streams will be *recorded* and you can watch them any time. I will send you the stream links in advance by email via kos.cvut.cz and they also will be published on the page https://courses.fit.cvut.cz/BIE-PS1/lectures/index.html[courses.fit.cvut.cz/BIE-PS1/lectures].

.Links for the first week
|===
|Stream type | Link

|Lecture 1 (Wed 23.9. 7:30)
|https://youtu.be/K4XHFKXFwI8

|Seminar 1 (Wed 23.9. 9:15)
|https://youtu.be/XUnKUZ5R3FE

|Seminar 1 (Wed 23.9. 11:00)
|https://youtu.be/jI0OV0yt6CI

|Seminar 1 (Wed 23.9. 12:45)
|https://youtu.be/kw7EkOx6mxI
|===

My primary goal is to keep high-quality lectures and seminars, therefore let me know about any problems you might encounter with this online teaching. *Use email trdlicka@fit.cvut.cz to communicate with me.*  Use of other communication channels could overwhelm me, so prefer this email which should enable me to respond fast. Do not forward your university mail outside, the primary information channel from us to you is email from kos.cvut.cz. Also, follow pages https://old.fit.cvut.cz/en/coronavirus[FIT-coronavirus] and https://courses.fit.cvut.cz/BIE-PS1, which is the primary source of materials for the course.


I wish you good health, pleasant study, and optimistic mood.

Ing. Jan Trdlička, Ph.D.


////
* Attention, *the second big test* will take place on *Wednesday 18.12.2019* during the practice. Repeat the following topics
** Regular expressions (metacharacters).
** Commands grep, sed, awk and.
** Scripts (script parameters, command test, if/then/else, loops for/while/until).
** Access permissions.
** And all previous topics.

* Attention, *the first big test* will take place on *Wednesday 13.11.2019* during the practice. Repeat the following topics
** CLI parsing order (metacharacters and their meaning),
** Shell variables and aliasing.
** Filesytem and file/directory commands.
** Filters.
** Command grep.

* 6.6.2019: The assignment of *the second task* was published.

* *Timetable*:  https://timetable.fit.cvut.cz/old/public/en/predmety/31/61/p3161206.html
////


