= 1. News
:imagesdir: media

*1.12.2020 - Week 11*

[square]
* The lecture 10 will be available at the following link link:https://youtu.be/6oOHob051Vs[YouTube]
* Seminars will be available at following links:
  ** 9:15-10:45 link:https://youtu.be/ji4cEN7Zdvc[YouTube]
  ** 11:00-12:30 link:https://youtu.be/wKluu8PVnR8[YouTube]
  ** 12:45-14:15 link:https://youtu.be/O_DW9W29Csw[YouTube]
* Here are some more information for tomorrow's class:
 ** There will be no small test tomorrow.
 ** Instead of a small test, another homework on link:https://learnshell.fit.cvut.cz[Learnshell] is prepared for you (deadline is 6.12.2020 at 23:00).

*24.11.2020 - Week 10*

[square]
* The lecture 9 will be available at the following link link:https://youtu.be/uEuIDdkG0mI[YouTube]
* Seminars will be available at following links:
  ** 9:15-10:45 link:https://youtu.be/lipFRJD7ia8[YouTube]
  ** 11:00-12:30 link:https://youtu.be/Ch-wqgP_NUY[YouTube]
  ** 12:45-14:15 link:https://youtu.be/Z9dAjE_k80o[YouTube]
* Here are some more information for tomorrow's class:
 ** There will be no small test tomorrow.
 ** Instead of a small test, another homework on link:https://learnshell.fit.cvut.cz[Learnshell] is prepared for you (deadline is 30.11.2020 at 23:00).

*17.11.2020 - Week 9*

[square]
* The lecture 8 will be available at the following link link:https://youtu.be/VbqoK6uv7J0[YouTube]
* Seminars will be available at link:https://go.microsoft.com/fwlink/p/?LinkID=873020&lm=deeplink&lmsrc=homePageWeb&cmpid=WebSignIn[MS Teams]
* Here are some more information for tomorrow's class:
 ** There will be no small test tomorrow.
 ** Instead of a small test, another homework on link:https://learnshell.fit.cvut.cz[Learnshell] is prepared for you (deadline is 22.11.2020 at 23:00).
 ** The second task is published at link:https://courses.fit.cvut.cz/BI-PS1/tasks/02/index.html[courses.fit.cvut.cz] (deadline is 22.11.2020 at 23:00).

*10.11.2020 - Week 8*

[square]
* The lecture 7 will be available at the following link link:https://youtu.be/yD4qkQ7pVFg[YouTube]
* Seminars will be available at link:https://go.microsoft.com/fwlink/p/?LinkID=873020&lm=deeplink&lmsrc=homePageWeb&cmpid=WebSignIn[MS Teams]. Please check that you see tomorrow's seminar in the MS Teams Calendar. If not, send me an email as soon as possible and I will include you in the appropriate group so that you can follow the seminar and write a small test in Learnshell.

* *Information for evaluation and obtaining assessment*
  ** For the following reasons, I decided to change the conditions for obtaining assessment
    *** With a high probability the restrictions regarding COVID-19 will last until the end of the semester and therefore it will not be possible to carry out large tests in the faculty classroom.
	*** It is almost impossible to prevent copying during tests and the use of unauthorized materials, ...
	 
  ** Therefore, I decided to replace the large tests with *an oral interview with each student through MS Teams, which will take place at the end of the semester (in the week of 14-18 December)*. I assume that the interview will last about 20 minutes and during which I would ask the student one theoretical question (eg explain what a symbolic link is, ...), one practical question (similar to a question in small tests) and possibly another supplementary question. The results of small tests will also be taken into account in determining the final grade.
  
  ** *Small tests will continue to take place at the beginning of each seminar* and are primarily intended to serve
    *** to motivate students for regular weekly and weekly preparation,
    *** as feedback on their current knowledge,
    *** to get an idea of ​​what types of problems they should be able to solve.

  ** If it was not possible to carry out a small test either due to eg a student's illness or due to technical problems (eg problems with network connection, problems with Learnshell), so for simplicity, I decided that *the small tests will not be replaced* and everything will be resolved during the oral interview.
  
*1.11.2020 - Week 7*

[square]
* The lecture 6 will be available at the following link link:https://youtu.be/yD4qkQ7pVFg[YouTube]
* Seminars will be available at link:https://go.microsoft.com/fwlink/p/?LinkID=873020&lm=deeplink&lmsrc=homePageWeb&cmpid=WebSignIn[MS Teams]

*1.11.2020 - Week 6*

[square]
* The lecture 5 will be available at the following link link:https://youtu.be/VvPhIw2fGpM[YouTube]
* Seminars will be available at link:https://go.microsoft.com/fwlink/p/?LinkID=873020&lm=deeplink&lmsrc=homePageWeb&cmpid=WebSignIn[MS Teams]

*23.10.2020 - Week 5*

Classes (lecture and seminars) will be canceled the next Wednesday, October 28, 2020, because it will be a public holiday.

*20.10.2020 - Week 4*

.Links for the fourth week
|===
|Stream type | Link

|Lecture 4 (Wed 14.10. 7:30)
|https://youtu.be/mZ8FrDhdhWU

|Seminar 4 (Wed 14.10. 9:15)
|https://youtu.be/eeAa9dnJQuc

|Seminar 4 (Wed 14.10. 11:00)
|https://youtu.be/Jpf72x7hpT0

|Seminar 4 (Wed 14.10. 12:45)
|https://youtu.be/VozkZzhCDdk
|===

A small test will take place at the beginning of the seminar. *Students can participate in the test only at the time when they have a seminar scheduled according to link:https://timetable.fit.cvut.cz/old/public/en/predmety/31/61/p3161206.html[KOS]*


*13.10.2020 - Week 3*

.Links for the fourth week
|===
|Stream type | Link

|Lecture 3 (Wed 14.10. 7:30)
|https://youtu.be/bDsl0rhDURQ

|Seminar 3 (Wed 14.10. 9:15)
|https://youtu.be/kmTrveziplE

|Seminar 3 (Wed 14.10. 11:00)
|https://youtu.be/kDDzZctDsVc

|Seminar 4 (Wed 14.10. 12:45)
|https://youtu.be/fg6p-i-Lyi8
|===


*5.10.2020 - Week 2*

.Links for the third week
|===
|Stream type | Link

|Lecture 2 (Wed 7.10. 7:30)
|https://youtu.be/K6E1PGsEV0k

|Seminar 2 (Wed 7.10. 9:15)
|https://youtu.be/seXtQqTT3N4

|Seminar 2 (Wed 7.10. 11:00)
|https://youtu.be/gTuT98qlyFs

|Seminar 3 (Wed 7.10. 12:45)
|https://youtu.be/hyhEMi2_eJI
|===


*29.9.2020 - Week 2*

.Links for the second week
|===
|Stream type | Link

|Lecture 2 (Wed 30.9. 7:30)
|https://youtu.be/JigA31MAMr0

|Seminar 2 (Wed 30.9. 9:15)
|https://youtu.be/Z7clsjyTbZw

|Seminar 2 (Wed 30.9. 11:00)
|https://youtu.be/b2olcwsROz8

|Seminar 2 (Wed 30.9. 12:45)
|https://youtu.be/tg8jdscUU8U
|===



*20.9.2020 - BI-ULI*

Module https://courses.fit.cvut.cz/BI-ULI[BI-ULI] (Introduction to Linux, 2 credits)  - auxiliary module especially for beginners. Students are enrolled in this course automatically and it will only depend on them whether they want to complete it (this is a bonus of gaining additional knowledge and additional credits).

*20.9.2020 - The course BIE-PS1 in winter semester 2020/21 (email sent via kos.cvut.cz)*

Dear students, regulations from the state, from the CTU rector and from the FIT dean do not allow contact classes and the both lectures and seminars must be implemented online. In BIE-PS1 I have made the following decisions:

The lectures and seminars will be realized as *live streams via Youtube in the scheduled time* (see the https://timetable.fit.cvut.cz/old/public/en/predmety/31/61/p3161206.html[timetable.fit.cvut.cz]). The streams will be *recorded* and you can watch them any time. I will send you the stream links in advance by email via kos.cvut.cz and they also will be published on the page https://courses.fit.cvut.cz/BIE-PS1/lectures/index.html[courses.fit.cvut.cz/BIE-PS1/lectures].

.Links for the first week
|===
|Stream type | Link

|Lecture 1 (Wed 23.9. 7:30)
|https://youtu.be/K4XHFKXFwI8

|Seminar 1 (Wed 23.9. 9:15)
|https://youtu.be/XUnKUZ5R3FE

|Seminar 1 (Wed 23.9. 11:00)
|https://youtu.be/jI0OV0yt6CI

|Seminar 1 (Wed 23.9. 12:45)
|https://youtu.be/kw7EkOx6mxI
|===

My primary goal is to keep high-quality lectures and seminars, therefore let me know about any problems you might encounter with this online teaching. *Use email trdlicka@fit.cvut.cz to communicate with me.*  Use of other communication channels could overwhelm me, so prefer this email which should enable me to respond fast. Do not forward your university mail outside, the primary information channel from us to you is email from kos.cvut.cz. Also, follow pages https://old.fit.cvut.cz/en/coronavirus[FIT-coronavirus] and https://courses.fit.cvut.cz/BIE-PS1, which is the primary source of materials for the course.


I wish you good health, pleasant study, and optimistic mood.

Ing. Jan Trdlička, Ph.D.


////
* Attention, *the second big test* will take place on *Wednesday 18.12.2019* during the practice. Repeat the following topics
** Regular expressions (metacharacters).
** Commands grep, sed, awk and.
** Scripts (script parameters, command test, if/then/else, loops for/while/until).
** Access permissions.
** And all previous topics.

* Attention, *the first big test* will take place on *Wednesday 13.11.2019* during the practice. Repeat the following topics
** CLI parsing order (metacharacters and their meaning),
** Shell variables and aliasing.
** Filesytem and file/directory commands.
** Filters.
** Command grep.

* 6.6.2019: The assignment of *the second task* was published.

* *Timetable*:  https://timetable.fit.cvut.cz/old/public/en/predmety/31/61/p3161206.html
////


