= 1. News
:imagesdir: media

* Attention, *the second big test* will take place on *Wednesday 18.12.2019* during the practice. Repeat the following topics
** Regular expressions (metacharacters).
** Commands grep, sed, awk and.
** Scripts (script parameters, command test, if/then/else, loops for/while/until).
** Access permissions.
** Command find.
** And all previous topics.

* Attention, *the first big test* will take place on *Wednesday 13.11.2019* during the practice. Repeat the following topics
** CLI parsing order (metacharacters and their meaning),
** Shell variables and aliasing.
** Filesytem and file/directory commands.
** Filters.
** Command grep.

* 6.6.2019: The assignment of *the second task* was published.

* *Timetable*:  https://timetable.fit.cvut.cz/old/public/en/predmety/31/61/p3161206.html

////

* *Retake test* will take place 8.1.2019, 15:00-17:00 in T9:349. *For this test is necessary to book the place in https://kos.cvut.cz !!!*.
** The „Retake Test“ is a bonus by which a student can repair a test from which he earned the least points.
** Example: Student earned the following points from all tests 5+10+3+20=38. If the student earn 17 points from „retake test“, then he/she has 5+10+17+20=52. If the student earn 1 points from „retake test“, then he/she has 5+10+1+20=36.
** In the test, there can any question from any topic explained in this module.
** The test answers will be evaluated either by a full number of points (correct solution) or by zero (bad / partial solution).

* *Test 3* will take place 18.12.2018, 14:30-16:00 or 16:15-17:45, in T9:350 (come to the lab you're signed in to). Repeat the following topics

** regular expressions (grep, sed and awk),
** access permissions (chmod and umask),
** find,
** processes and threads,
** archiving and data compression.
** numeric calculations,
** any previous topics.

* *Test 2* will take place 20.11.2018, 14:30-16:00 or 16:15-17:45, in T9:350 (come to the lab you're signed in to). Repeat the following topics
** command test and flow control,
** filesystem,
** I/O redirection and UNIX filters.

* *Test 1* will take place 23.10.2018 14:30-16:00 or 16:15-17:45, in T9:350 (come to the lab you're signed in to). Repeat the following topics
** UNIX manual (commands man/help),
** Secure shell (commands ssh/scp),
** Basic commands,
** CLI parsing order (metacharacters and their meaning),
** Shell variables.
////

* Module https://courses.fit.cvut.cz/BI-ULI[BI-ULI] (Introduction to Linux, 2 credits)  - auxiliary module especially for beginners. Students can subscribe to this e-learning module (by email to the Study Department).
