= Homework for the 1st practice

== Topics of the current practice

++++
<style>li details { margin-bottom: 0.5em; }</style>
<div class='olist arabic'>
<ol class='arabic'>
<li><details><summary>Create a variable <code>DELIMITER</code> and set a colon value (<code>:</code>)</summary>
++++
....
DELIMITER=:
....
++++
</details></li>
<li><details><summary>List the value of the variable <code>DELIMITER</code>  using the command <code>declare</code></summary>
++++
....
declare -p DELIMITER
....
++++
</details></li>
<li><details><summary>List the value of the variable <code>DELIMITER</code> using the command <code>printf</code> (value will end with a new line).</summary>
++++
....
printf '%s\n' "$DELIMITER"
....
++++
</details></li>
<li><details><summary>List the value of the variable <code>USER</code></summary>
++++
....
declare -p USER
....
++++
</details></li>
<li><details><summary>Use the command <code>getent passwd username</code> to list your user account information, replace <code>username</code> manually with your user name.</summary>
++++
....
getent passwd barinkl
....
++++
</details></li>
<li><details><summary>Use the previous command, but use a variable <code>USER</code> instead of the handwritten user name.</summary>
++++
....
getent passwd "$USER"
....
++++
<p>Use the key <code>arrow_up</code> to invoke the previous command, key <code>CTRL+arrow_left</code> to jump a word to the left, key <code>CTRL+K</code></p> to delete to the end of the line.
</details></li>
<li><details><summary>Use the command <code>tr</code>  to replace  all instances of the character <code>:</code> with a new line (<code>\n</code>) e in the output of the previous command. The first argument of <code>tr</code> will be <code>:</code> and the second argument will be <code>\n</code>. Be aware that the character <code>\</code> has a special meaning in the shell and should be used <code>'</code> <code>'</code></summary>
++++
....
getent passwd "$USER" | tr : '\n'
....
++++
</details></li>
<li><details><summary>In the previous command, replace <code>:</code> with the value of the variable <code>DELIMITER</code>.</summary>
++++
....
getent passwd "$USER" | tr "$DELIMITER" '\n'
....
++++
</details></li>
<li><details><summary>Save the output of the previous command to a file <code>username-info</code>, where <code>username</code> is replaced by the variable value <code>USER</code>.</summary>
++++
....
getent passwd "$USER" | tr "$DELIMITER" '\n' > "$USER-info"
....
++++
</details></li>
<li><details><summary>Use the command <code>ls</code> to determine that the file is actually created and what is its size.</summary>
++++
....
ls -l "$USER-info"
....
++++
</details></li>
<li><details><summary>Use the command <code>wc</code> and the previous command to calculate the number output lines of command <code>getent</code> (that is, the number of rows after replacing <code>:</code> with a new line).</summary>
++++
....
getent passwd "$USER" | tr "$DELIMITER" '\n' | wc -l
....
++++
</details></li>
<li><details><summary>Use the command <code>less</code>  to read the contents of the created file (then end the command), use a tab to complete the file name.</summary>
++++
....
less bar<TAB>
less barinkl-info
<q>

# <TAB> means pressing key TAB
# <q> means pressing key q
....
++++
</details></li>
<li><details><summary>Count the number of lines of the created file and compare (manually) with the result of counting items (use the key <code>arrow_up</code> to browse the history.</summary>
++++
....
getent passwd "$USER" | tr "$DELIMITER" '\n' | wc -l; wc -l "$USER-info"
....
++++
</details></li>
<li><details><summary>Create an file <code>man.nl</code> to store the number of lines of manual page of  the command <code>man</code>.</summary>
++++
....
man man | wc -l >man.nl
....
++++
</details></li>
<li><details><summary>Calculate the number of lines from the output of the previous example (should be 0 because all text is saved to file or is pointing to error output).</summary>
++++
....
man man | wc -l >man.nl | wc -l
....
++++
</details></li>
<li><details><summary>Use the command <code>rm file</code>  to delete the created files, instead of <code>file</code> enter the name/names of the file/files.</summary>
++++
....
rm "$USER-info" man.nl
....
++++
</details></li>
<li><details><summary>Calculate the number of entries in the working directory</summary>
++++
....
ls | wc -l
# Beware ls -l, there is a line with total
ls -l | wc -l
....
++++
</details></li>
<li><details><summary>Use the command <code>ls</code> to verify that the files have been deleted.</summary>
++++
....
ls "$USER-info" man.nl
....
++++
</details></li>
<li><details><summary>Count the number of entries in the working directory again.</summary>
++++
....
ls | wc -l
....
++++
</details></li>
<li><details><summary>Vytvořte proměnnou <code>A</code> s hodnotou <code>abc</code> a proměnnou <code>B</code> s hodnotou <code>def</code></summary>
++++
....
A=abc
B=def
....
++++
</details></li>
<li><details><summary>Create a variable <code>C</code> by concatenating the variable values <code>A</code> and <code>B</code>.</summary>
++++
....
C="$A$B"
....
++++
</details></li>
<li><details><summary>List the values of variables <code>A</code>, <code>B</code>, and <code>C</code></summary>
++++
....
declare -p A B C
....
++++
</details></li>
<li><details><summary>Add the string <code>ghi</code> to the end of the variable <code>C</code>. </summary>
++++
....
C="$C"ghi
# eventually for more advanced
C+=ghi
....
++++
</details></li>
<li><details><summary>Make sure the variable <code>C</code> has a value <code>abcdefghi</code>.</summary>
++++
....
declare -p C
....
++++
</details></li>
<li><details><summary>Calculate the length (number of characters) of the variable <code>C</code> using commands <code>printf</code> and <code>wc</code>.</summary>
++++
....
printf '%s' "$C" | wc -c
# try that when you use an echo that adds a new line character, the result is wrong
echo "$C" | wc -c
....
++++
</details></li>
<li><details><summary>Create a variable <code>text</code> in which to store several lines of text (use <code>'</code> <code>'</code> or <code>"</code> <code>"</code>)</summary>
++++
....
text='several
text
lines'
....
++++
</details></li>
<li><details><summary>Create a variable <code>kitty</code> with the following content:
++++
....
 /\__/\                                                                         
(='><'=)
 (")(")_/`
....
++++
</summary>
++++
....
kitty=' /\__/\
 (='"'><'"'=)
  (")(")_/`'
....
++++
</details></li>
<li><details><summary>List the contents of the variable <code>kitty</code>,  to look like in the assignment.</summary>
++++
....
printf '%s\n' "$kitty"
....
++++
</details></li>
<li><details><summary>See the manual page of the command <code>man</code>.</summary>
++++
....
man man
....
++++
</details></li>
<li><details><summary>Find the string <code>ENVIRONMENT</code> in the previous manual page.  What variable is used to set up the man page browser?</summary>
++++
....
/ENVIRONMENT

#The PAGER variable is used to set the man page browser (pager).
....
++++
</details></li>
<li><details><summary>If you type an assignment in a variable before the command name, it is performed for the specified command, for example: <code>COLUMNS=200 ls /</code>. Set the pager to display only the number of words and lines in the man page instead of displaying the man page and call up the command manual <code>man</code>.</summary>
++++
....
PAGER='wc -wl' man man
....
++++
</details></li>
<li><details><summary>Run the command <code>sleep 1000</code> and exit after a while.</summary>
++++
....
sleep 1000
<CTRL+C>
....
++++
</details></li>
<li><details><summary>Save the value of variable <code>PS1</code> in the variable <code>oldPS1</code></summary>
++++
....
oldPS1="$PS1"
....
++++
</details></li>
<li><details><summary>Set the variable <code>PS1</code> to prompt to display the current time, user name and current directory, and end with character <code>></code>.</summary>
++++
....
PS1='\t \u \w> '
....
++++
</details></li>
<li><details><summary>Set the variable <code>PS1</code> to its original value with <code>oldPS1</code>.</summary>
++++
....
PS1="$oldPS1"
....
++++
</details></li>
</ol>
</div>
++++ 


== Topics of the next practice

++++
<div class='olist arabic'>
<ol class='arabic'>
<li><details><summary>See the manual page of the command <code>date</code> (and any related pages [SEE ALSO]), and especially formatting strings (%_)</summary>
++++
....
man date

# on server fray1/fray3
man date
/SEE ALSO
man -s 3 strftime
....
++++
</details></li>
<li><details><summary>Write the following text (2 lines) with the current values (do not solve the text language) with one <code>date</code> call:
++++
....
Today is Monday,  1.10.2018 (40. week).
Now is 12:34:56 [CEST].
....
++++
</summary>
++++
....
date '+Today is %A, %e.%m.%Y (%W. week)%nNow is %T [%Z].'
....
++++
</details></li>
<li><details><summary>Refer to the documentation  of the command <code>printf</code></summary>
++++
....
type printf
help printf
man printf
man 3 printf
....
++++
</details></li>
<li><details><summary>Use the command <code>printf</code> and the special character <code>*</code> to list the names of all entries in the current directory, separated by a TAB.</summary>
++++
....
printf '%s\t' *
....
++++
</details></li>
<li><details><summary>List the entries of the current directory in 3 columns of 25 characters each.</summary>
++++
....
printf '%25s%25s%25s\n' *
printf '%-25s%-25s%-25s\n' *
....
++++
</details></li>
<li><details><summary>Log in to the server <code>fray1.fit.cvut.cz</code> three times at 1-minute intervals

V minutových intervalech se 3x přihlaste na <code>fray1.fit.cvut.cz</code>  and run the command <code>date</code>.</summary>
++++
....
ssh fray1.fit.cvut.cz date; sleep 60; ssh fray1.fit.cvut.cz date; sleep 60; ssh fray1.fit.cvut.cz
# případně
SSH='ssh fray1.fit.cvut.cz date'
S='sleep 60'
$SSH; $S; $SSH; $S; $SSH
....
++++
</details></li>
<li><details><summary>Log in to the server <code>fray1.fit.cvut.cz</code> and run the command <code>date</code> three times at 1 minute intervals. </summary>
++++
....
ssh fray1.fit.cvut.cz 'date; sleep 60; date; sleep 60; date'
....
++++
</details></li>
<li><details><summary>List details about directory <code>/bin</code> on the local computer and the server <code>fray1.fit.cvut.cz</code>, compare the outputs.</summary>
++++
....
ls -l /bin
ssh fray1.fit.cvut.cz 'ls -l /bin'
....
++++
</details></li>
<li><details><summary>See the manual page of the command <code>ls</code>, , especially the list and sort switches(<code>-a</code>, <code>-l</code>, <code>-d</code>, <code>-S</code>, <code>-t</code>, <code>-r</code>)</summary>
++++
....
man ls
....
++++
</details></li>
<li><details><summary>Sort the current directory listing, including details by alphabet, size and file modification time, or in reverse order.</summary>
++++
....
ls -l
ls -lt
ls -lS
ls -ltr
ls -lSr
....
++++
</details></li>
<li><details><summary>List the contents of the directory <code>/bin</code>.</summary>
++++
....
ls /bin
....
++++
</details></li>
<li><details><summary>On server <code>fray1.fit.cvut.cz</code> use the command <code>fgrep text</code>, to print the lines from the file <code>/etc/profile</code>, where <code>text</code> replace with the search string containing a) <code>=</code>, b) <code>-</code>, c) <code>.</code>, d) <code>"</code>, e) <code>'</code>, f) <code>#</code>.</summary>
++++
....
ssh fray1.fit.cvut.cz 'fgrep = /etc/profile'
ssh fray1.fit.cvut.cz 'fgrep - /etc/profile'
ssh fray1.fit.cvut.cz 'fgrep . /etc/profile'
ssh fray1.fit.cvut.cz 'fgrep \" /etc/profile'
ssh fray1.fit.cvut.cz "fgrep \' /etc/profile"
ssh fray1.fit.cvut.cz 'fgrep \# /etc/profile'
....
++++
</details></li>
</ol>
</div>
++++ 
