= Homework for the 8th practice

== Topics of the current practice

++++
<style>li details { margin-bottom: 0.5em; }</style>
<div class='olist arabic'>
<ol class='arabic'>
<li><details><summary>(In Solaris - fray1/fray3): Set the variable <code>PATH</code> so that GNU versions of the commands from the directory <code>/usr/gnu/bin</code> are primarily started.</summary>
++++
....
PATH=/usr/gnu/bin:$PATH
....
++++
</details></li>
<li><details><summary>Enter the directory <code>/home/courses/BIPS1/public/re</code>.</summary>
++++
....
cd /home/courses/BIPS1/public/re
....
++++
</details></li>
<li><details><summary>The last item in file <code>apache.log</code> is the size of the data sent or the character <code>-</code>,  if the data was not sen. Calculate how many requests (log entries) did not send data (the last entry is <code>-</code> ).</summary>
++++
....
grep -c -- '-$' apache.log
grep -c -e '-$' apache.log
grep -c ' -$' apache.log 
....
++++
</details></li>
<li><details><summary>The penultimate entry in file <code>apache.log</code>  is a three-digit status code. List the status codes (penultimate entry) that did not send data (the last entry is <code>-</code> ).</summary>
++++
....
grep -o '... -$' apache.log | cut -c1-3 | sort -u
....
++++
</details></li>
<li><details><summary>In the previous example, list which status code was most common. Save this status code in a variable <code>CODE</code> .</summary>
++++
....
grep -o '... -$' apache.log | cut -c1-3 | sort | uniq -c | sort -n | tail -n 1 | grep -o '...$'
CODE=$(grep -o '... -$' apache.log | cut -c1-3 | sort | uniq -c | sort -n | tail -n 1 | grep -o '...$')
....
++++
</details></li>
<li><details><summary>The first line of the HTTP request is enclosed in quotation marks in the log and contains <code>"method URL HTTPversion"</code>. List what the different methods were for requests that ended with a status code in the CODE variable and did not send any data.</summary>
++++
....
grep " $CODE -$" apache.log | egrep -o '"[^ ]+' | sort -u | cut -c2-
....
++++
</details></li>
<li><details><summary>List which URLs were most common for requests that ended with a status code in the CODE variable and did not send any data.</summary>
++++
....
grep " $CODE -$" apache.log | egrep -o '"[^"]+"' | sort | uniq -c | sort -n| tail -n 1 | cut -d\" -f2 | cut -d' ' -f2
....
++++
</details></li>
<li><details><summary>Calculate how many requests ended with a status code of 200. List the number of requests and the percentage of all requests.</summary>
++++
....
c=$(egrep -c " 200 [^ ]+$" apache.log)
n=$(wc -l <apache.log)
printf '%d %d%%\n' $c $((100*c/n))
....
++++
</details></li>
<li><details><summary>When using a simpler RE (regular expression) <code>" 200 "</code> in the previous example, the results would be incorrect by one row. List which it would be.</summary>
++++
....
egrep " 200 [^ ]+$" apache.log >~/good
grep " 200 " apache.log >~/bad
diff ~/good ~/bad
rm ~/good ~/bad
....
++++
</details></li>
<li><details><summary>The URL can include a query string that begins with a character <code>?</code> . For requests with status code 200, list which different extensions of the requested files contain the query string.</summary>
++++
....
egrep " 200 [^ ]+$" apache.log | cut -d\" -f2 -s | grep -o '/[^/]*\.[^.?]*?' | grep -o '\.[^.?]*' | sort -u
....
++++
</details></li> 
<li><details><summary>Add all sizes of sent data with status code 200. (Help, use the <code>paste</code> command and the shell arithmetic expression.)</summary>
++++
....
echo $(( $(egrep " 200 [^ ]+$" apache.log | egrep -o ' [0-9]+$' | paste -d+ -s) + 0))

# It will be easier
awk '$(NF-1)==200 {sum+=$NF} END {print sum}' apache.log
....
++++
</details></li>
<li><details><summary>List rows that have the longest path (number of directories) - rows contain the most slashes.</summary>
++++
....
C=$(tr -dc '/\n' <apache.log | sort -u | tail -n 1 | wc -c)
((C--))
egrep "(/.*){$C}" apache.log
....
++++
</details></li>
<li><details><summary>List the number of requests for  files with extensions <code>jpg</code> or <code>png</code> .</summary>
++++
....
egrep -c '\.(jpg|png)[ ?]' apache.log
....
++++
</details></li>
</ol>
</div>
++++ 



