= 3. Classification 
//:imagesdir: ../media/classification


* *This module is finished by the graded assessment*, therefore the continuous work in the semester is evaluated.

== Tests

* During the semester, *the student will write several tests to earn points*.
* The tests will be held continuously during the semester so that *the student is motivated to prepare continuously*.
* *Therefore, there will be no repair tests!*
* There will be two types of tests during the semester:
** *Small tests*
*** They will take place *at the beginning of each practice* (from the 3rd week of semester).
*** The test duration will be around *5-10 minutes*.
*** They will usually verify knowledge of topics discussed in the previous week.
*** Student can obtain up to *40 points* from all these tests.

** *Big tests*
*** They will take place *in the middle (week 8, 11.11.2020)*nd *at the end (week 13, 15.12.2020)* of the semester.
*** The test duration will be around *60 minutes*.
*** They will verify knowledge of all discussed topics.
*** Student can obtain up to *60 points* from all these tests.

* *Absence from the test means 0 points from the test (exception is only serious reason).*

== Home tasks

* In addition, it is possible to earn an extra *3 points*, which are assigned at the end of the semester. 
* They are awarded for the successful solution of home tasks. 
* These tasks will be continuously assigned at seminars or lectures.

== Evaluation scale

[options="autowidth"]
|====
<h| Grade +
ECTS  <h| Points   <h| Evaluation in words
| A       | more than 89   | excellent
| B       | 80 – 89        | very good
| C       | 70 – 79        | good
| D       | 60 – 69        | satisfactory
| E       | 50 – 59        | sufficient
| F       | less than  50  | failed
|====
