= 3. Classification 
//:imagesdir: ../media/classification


* *This module is finished by the graded assessment*, therefore the continuous work in the semester is evaluated.

== Tests

* During the semester, *the student will write several tests to earn points*.
* The tests will be held continuously during the semester so that *the student is motivated to prepare continuously*.
* *Therefore, there will be no repair tests!*

* They will take place *at the beginning of each practice* (from the 5rd week of semester).
* The test duration will be around *5-10 minutes*.
* They will usually verify knowledge of topics discussed in the previous week.
* Student can obtain up to *30 points* from all these tests.

* *Absence from the test means 0 points from the test (exception is only serious reason).*

== Oral interview

* Interviews will take place *during the last two weeks of the semester* at times reserved for BIE-UOS lectures and tutorials. 
* The student will come to the classroom on the given date, which he/she has reserved (interviews will not take place in a distance form).
* The student will receive a *question similar to the questions that were in the tests on Learnshell or that are in the solved examples*, and will try to solve it on a computer. 
* If in doubt about the student's knowledge, he/she may be given a supplementary question(s).
* Student can obtain up to *70 points* from the interview.

== Tasks

* In addition, it is possible to earn an extra *3 points*, which are assigned at the end of the semester. 
* They are awarded for the successful solution of tasks. 
* These tasks will be continuously assigned at tutorials or lectures (see link:Tasks/index.html[Tasks]).

== Evaluation scale

[options="autowidth"]
|====
<h| Grade +
ECTS  <h| Points   <h| Evaluation in words
| A       | more than 89   | excellent
| B       | 80 – 89        | very good
| C       | 70 – 79        | good
| D       | 60 – 69        | satisfactory
| E       | 50 – 59        | sufficient
| F       | less than  50  | failed
|====
