= Homework for the 10th practice

== Topics of the current practice

++++
<style>li details { margin-bottom: 0.5em; }</style>
<div class='olist arabic'>
<ol class='arabic'>
<li><details><summary>(In Solaris - fray1/fray3): Set the variable <code>PATH</code> so that GNU versions of the commands from the directory <code>/usr/gnu/bin</code> are primarily started.</summary>
++++
....
PATH=/usr/gnu/bin:$PATH
....
++++
</details></li>
<li><details><summary>Save the output of the command <code>getent passwd</code> to a file <code>passwd</code> .</summary>
++++
....
getent passwd >passwd
....
++++
</details></li>
<li><details><summary>Use the command <code>awk</code> to list the number of lines in the file <code>passwd</code>. </summary>
++++
....
awk 'END { print NR }' passwd
....
++++
</details></li>
<li><details><summary>Use the command <code>awk</code> to list only the 3rd column (UID) of the file <code>passwd</code> .</summary>
++++
....
awk -F: '{ print $3 }' passwd
....
++++
</details></li>
<li><details><summary>Use the command <code>awk</code> to write the highest UID from the file <code>passwd</code> in one pass.</summary>
++++
....
awk -F: '$3 > max { max = $3 }; END { print max }' passwd
....
++++
</details></li>
<li><details><summary>Use the command <code>awk</code> to list the user name of the user with the highest UID from the file  <code>passwd</code> in one pass .</summary>
++++
....
awk -F: '$3 > max { max = $3; user = $1 }; END { print user }' passwd
....
++++
</details></li>
<li><details><summary>List the real name of all users (5th column) from the file <code>passwd</code> , which you convert to lowercase using function  <code>tolower()</code>.</summary>
++++
....
awk -F: '{ print tolower($5) }' passwd
....
++++
</details></li>
<li><details><summary>Add the username (column 1) to the beginning of the line in the output of the previous example.</summary>
++++
....
awk -F: '{ print $1,tolower($5) }' passwd
....
++++
</details></li>
<li><details><summary>List only the username and last name (family name) from the output of the previous example.</summary>
++++
....
awk -F: '{ print $1,tolower($5) }' passwd | awk '{ print $1,$3 }'
....
++++
</details></li>
<li><details><summary>In the previous example, write only the first 5 characters of the username and last name using the function <code>substr()</code> .</summary>
++++
....
awk -F: '{ print $1,tolower($5) }' passwd | awk '{ print substr($1,1,5),substr($3,1,5) }'
....
++++
</details></li>
<li><details><summary>Use the function <code>length()</code> to calculate the average length of a user name (5th column) from a file <code>passwd</code> .</summary>
++++
....
awk -F: '{ L += length($5) }; END { print L/NR }' passwd
....
++++
</details></li>
<li><details><summary>List the line with the longest user name (5th column) from the file <code>passwd</code> .</summary>
++++
....
awk -F: 'NR == 1 { LINE=$0; }; { L = length($5) }; L > max { max = L; LINE=$0 }; END { print LINE }' passwd
....
++++
</details></li>
<li><details><summary>List the longest user name (5th column) from the file <code>passwd</code> .</summary>
++++
....
awk -F: 'NR == 1 { LINE=$0; }; { L = length($5) }; L > max { max = L; LINE=$5 }; END { print LINE }' passwd
....
++++
</details></li>
</div>
++++ 
