= Homework - permissions (access rights)

++++
<style>li details { margin-bottom: 0.5em; }</style>
<div class='olist arabic'>
<ol class='arabic'>

<li><details><summary>Create the following file and directory in the directory <code>/tmp</code> 
<pre>
d1
d1/hello.sh       # script that writes "Hello world" to standard output
d1/date           # copy of /usr/bin/date
</pre>
Create a variable <code>DIR</code>, <code>FILE1</code> and <code>FILE2</code> that will contain the absolute path to <code>d1</code>, <code>d1/hello.sh</code>, and <code>d1/date</code>, respectively.
</summary>
++++
....
cd /
mkdir d1
echo "#! /bin/bash" > d1/hello.sh
echo "echo 'Hello word'" >> d1/hello.sh
cp /usr/bin/date d1
export DIR="/tmp/d1"
export FILE1="/tmp/d1/hello.sh"
export FILE2="/tmp/d1/date"
....
++++
</details></li>

<li><details><summary>For a file defined by variable <code>FILE1</code>, set the following access rights <code>rwxr-----</code>.</summary>
++++
....
##################
#   Solution 1   #
##################
chmod u=rwx,g=r,o= "$FILE1"
....
....
##################
#   Solution 2   #
##################
chmod 740 "$FILE1"
....
++++
</details></li>

<li><details><summary>For a file defined by variable <code>FILE1</code>, remove the read right for the group and add the execute right for other.</summary>
++++
....
chmod g-r,o+x "$FILE1"
....
++++
</details></li>

<li><details><summary>For the directory and files defined by variables <code>DIR</code>, <code>FILE1</code>, and <code>FILE2</code>, respectively, remove all rights.</summary>
++++
....
chmod  000 "$FILE1"
chmod  000 "$FILE2"
chmod 000 "$DIR"
....
++++
</details></li>

<li><details><summary>Set the minimum rights to list only names of items that are in the directory defined by variable <code>"$DIR"</code> (the minimum rights are those with the smallest sum of weights) and verify.  Suppose you have no knowledge of the contents of the directory.</summary>
++++
....
##################
#   Solution 1   #
##################
chmod u+r "$DIR"
ls "$DIR" 2>/dev/null
....
....
##################
#   Solution 2   #
##################
chmod 400 "$DIR"
ls "$DIR" 2>/dev/null
....
++++
</details></li>


</ol>
</div>
++++ 



