= Homework for the 5th practice

== Topics of the current practice

++++
<style>li details { margin-bottom: 0.5em; }</style>
<div class='olist arabic'>
<ol class='arabic'>
<li><details><summary>Log on to the computer <code>fray1.fit.cvut.cz</code> .</summary>
++++
....
ssh username@fray1.fit.cvut.cz
....
++++
</details></li>
<li><details><summary> Go to the directory <code>/bin</code> (set the working directory to this directory).</summary>
++++
....
cd /bin
....
++++
</details></li>
<li><details><summary>Find out the details of the working directory and the directory <code>/bin</code> .</summary>
++++
....
ls -ld . /bin
stat . /bin
....
++++
</details></li>
<li><details><summary>List the absolute path to the working directory.</summary>
++++
....
pwd
printf -- '%s\n' "$PWD"
printf -- '%s\n' ~+
....
++++
</details></li>
<li><details><summary>List the i-node number of the parent directory.</summary>
++++
....
ls -id ..
stat -c %i ..
....
++++
</details></li>
<li><details><summary>Go to the parent directory and find out its i-node number.</summary>
++++
....
cd ..
ls -id .
stat -c %i .
....
++++
</details></li>
<li><details><summary>Return to the previous directory and repeat the previous two examples, but this time save the i-node numbers in variables <code>p1</code> and <code>p2</code>. If the i-node numbers differ, type in the following text: <code>i-nodes are different</code> to standard output.</summary>
++++
....
cd -
p1=$(stat -c %i ..)
cd ..
p2=$(stat -c %i .)
((p1 != p2)) && echo "i-nodes are different"
((p1 == p2)) || echo "i-nodes are different"
....
++++
</details></li>
<li><details><summary>Go to the directory <code>/bin</code> and from it to the physically superior directory and write its i-node number.</summary>
++++
....
cd /bin
cd -P ..
ls -id .
stat -c %i .
....
++++
</details></li>
<li><details><summary>Create a directory <code>logs</code> in your home directory. Create subdirectories <code>YYYY/MM</code> in this directory, where <code>YYYY</code> is from 2016 to 2019 and <code>MM</code> is from 01 to 12.</summary>
++++
....
cd
mkdir -p logs/{2016..2019}/{01..12}
....
++++
</details></li>
<li><details><summary>Inside the directories (<code>MM</code>) create files <code>DD.log</code>, whrere <code>DD</code> is from 01 to 31.</summary>
++++
....
touch logs/{2016..2019}/{01..12}/{01..31}.log
....
++++
</details></li>
<li><details><summary>In your home directory, create a symbolic link named  <code>today</code>, which refers to a log file according to the current day.</summary>
++++
....
ln -s "$(date '+logs/%Y/%m/%d.log')" today
....
++++
</details></li>
<li><details><summary>To the file <code>today</code> write the following text: <code>Last modification - HH:MM:SS</code>, where <code>HH:MM:SS</code> is the current time.</summary>
++++
....
date '+Last modification - %T' > today
....
++++
</details></li>
<li><details><summary>Move the file <code>today</code> to the directory <code>logs</code> and try to list the content of the file <code>today</code> after moving .</summary>
++++
....
mv today logs
more logs/today
....
++++
</details></li>
<li><details><summary>Remove the broken symbolic link <code>today</code> and create a new one containing the absolute path to the current log file.</summary>
++++
....
rm logs/today
ln -s ~/logs/$(date +%Y/%m/%d).log logs/today
....
++++
</details></li>
<li><details><summary>List the contents of the file <code>today</code>, move it to your home directory and list its content again.</summary>
++++
....
more logs/today 
mv logs/today ~
more today 
....
++++
</details></li>
<li><details><summary>Rename the directory <code>logs</code> to <code>log</code> and list the contents of the file <code>today</code>.</summary>
++++
....
mv logs log
more today
....
++++
</details></li>
<li><details><summary>Replace the symbolic link <code>today</code> with hard(link) <code>today</code> and list the contents of this file.</summary>
++++
....
rm today
ln log/$(date +%Y/%m/%d).log today
more today
....
++++
</details></li>
<li><details><summary>Move the link <code>today</code> to the directory <code>log</code> and rename the directory <code>log</code> to <code>logs</code>. List the contents of the file  <code>today</code> again.</summary>
++++
....
mv today log
mv log logs
more logs/today
....
++++
</details></li>
<li><details><summary>List the i-node number of link <code>today</code> and the current log file. Save these numbers in variables <code>i1</code> and <code>i2</code> and if the values are the same, write the text: <code>i-nodes match</code> to the standard output.</summary>
++++
....
ls -i logs/today "logs/$(date +%Y/%m/%d.log)"
i1=$(stat -c %i logs/today)
i2=$(stat -c %i "logs/$(date +%Y/%m/%d.log)")
((i1 == i2)) && echo "i-nodes match"
....
++++
</details></li>
<li><details><summary>Create a symbolic link in your home directory <code>today</code>, which refers to a file <code>logs/today</code>. Compare i-node numbers of the link <code>today</code> and the log file as in the previous example.</summary>
++++
....
ln -s logs/today
ls -i today
ls -iL today
i1=$(stat -c %i today)
i2=$(stat -Lc %i today)
((i1 == i2)) && echo "i-nodes match"
....
++++
</details></li>
<li><details><summary>Delete the entire directory <code>logs</code> including its content and link <code>today</code>.</summary>
++++
....
\rm -r logs today
....
++++
</details></li>
</ol>
</div>
++++ 


== Topics of the next practice

++++
<div class='olist arabic'>
<ol class='arabic'>
<li><details><summary>Create a file named <code>file</code> with lines containing letters <code>a</code> to <code>z</code>, each letter on a separate line.</summary>
++++
....
printf '%s\n' {a..z} >file
....
++++
</details></li>
<li><details><summary>Use the command <code>nl</code> to number the lines in the file <code>file</code>. Be careful not to delete the contents of the file.</summary>
++++
....
nl file >file.new
mv file{.new,}
....
++++
</details></li>
<li><details><summary>Add the text <code>Lines: N</code> to the end of the file, where <code>N</code> is the total number of lines in the file.</summary>
++++
....
printf 'Lines: %d\n' $(( $(wc -l <file) + 1 )) >>file
....
++++
</details></li>
<li><details><summary>Load contents of the file <code>file</code> into a variable <code>content</code>. Using construction <code>${var^^}</code>, which 
converts lowercase letters to uppercase during expansion of the variable <code>var</code>, overwrite the file contents with a value of the variable <code>content</code>.</summary>
++++
....
content=$(<file)
printf '%s\n' "${content^^}" >file
....
++++
</details></li>
<li><details><summary>In the file <code>file</code> delete the last line.</summary>
++++
....
head -$(( $(wc -l <file) - 1 )) file >file.new
mv file{.new,}

# another solution if the command head allows you to specify a negative number of rows
head -n -1 file >file.new
mv file{.new,}
....
++++
</details></li>
<li><details><summary>List the contents of the file <code>file</code> sorted alphabetically.</summary>
++++
....
sort file

# Be careful to sort numbers alphabetically!
....
++++
</details></li>
<li><details><summary>List the contents of the file <code>file</code> sorted numerically according to the first column, but in reverse order.</summary>
++++
....
sort -rn file
....
++++
</details></li>
++++
++++
</ol>
</div>
++++ 
